[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arbitrary = { version = "1.3.2", features = ["derive"] }
thiserror = "1.0.61"

[dev-dependencies]
arbtest = "0.3.1"
